### ISSUE TITLE
docblock indentation issue in PHPCS 2.9.1

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1760]
Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed incorrectly fixes a docblock resulting in two spaces being added to each docblock line.

### Case
first line of a dock block has two leading spaces before a tab

```php
class LoginViewLogin extends JViewLegacy
{
	/**
	 * Display the view.
	 *
	 * @param   string  $tpl  The name of the template file to parse.
	 *
	 * @return  void
	 *
	 * @since  3.7.0
	 */
```
Correctly reports spaces are not allowed use tabs
auto fixer removes the two spaces and "corrects" the indentation
normally one space will be needed on each of the following docblock lines but the fixer added 1-2 spaces to every line
```php
class LoginViewLogin extends JViewLegacy
{
	  /**
	   * Display the view.
	   *
	   * @param   string  $tpl  The name of the template file to parse.
	   *
	   * @return  void
	   *
	   * @since  3.7.0
	   */
```
the correct change should have only been to remove the tab. as follows
```php
class LoginViewLogin extends JViewLegacy
{
	/**
	 * Display the view.
	 *
	 * @param   string  $tpl  The name of the template file to parse.
	 *
	 * @return  void
	 *
	 * @since  3.7.0
	 */
```
see this PR where the issue was identified
https://github.com/joomla/joomla-cms/pull/18842#discussion_r152990913

file where the issue was identified
[joomla-cms/administrator/components/com_login/views/login/view.html.php](https://github.com/joomla/joomla-cms/blob/3.8.2/administrator/components/com_login/views/login/view.html.php)

Additionally no errors occur on subsequent checks with the incorrectly indented docblock with a tab followed by three spaces which should be a tab followed by a single space on secondary lines

**Comment by jrfnl** [comment]
@photodude We ran into the same thing with WP. I believe open PR #1599 which I created then should fix this for you. Would you mind testing to see if your usecase if sufficiently covered by it ?

**Comment by photodude** [comment]
@jrfnl I'm using PHPCS 2.9.1 I'm not set up for testing with PHPCS 3.x
Unfortunately, I don't have the time right now to backport your changes to PHPCS 2.9.1 for testing.

**Comment by photodude** [comment]
@jrfnl Looking at the changes again it didn't seem too bad on the changes to attempt a backport, 
Assuming I made all of the changes correctly, this did not fix the issue and introduced a new problem. 
in the original, we had `space space tab` throwing an error
```sh
••»/**
»•*
```
with the proposed changes, both lines now throw an error for use of a space. when only the first line is the problem.

The additionally the auto fixer did not fix anything after the change.

Gist of the changed file following what was proposed in PR #1599
https://gist.github.com/photodude/86dac624973529585db22fc739ce2d07

**Comment by jrfnl** [comment]
Just checking: are you sure the second line isn't `space space tab space` ? The adjusted sniff should not throw an error for `tab space` on a second comment line, but should for `space space tab (space)` - which it previously didn't as it would ignore subsequent comment lines -. Then again, this is a docblock, so that shouldn't be the reason... hmm...

I'll may have to have another look, but won't have time until next week.

**Comment by photodude** [comment]
Yes, the second line in the original file is `tab space`
the source sniff does not throw an error for the second line with the `tab space`, only on the first line with the `space space tab`

**Comment by jrfnl** [comment]
Well, at least that part of the fixes to the sniff should work ;-)

**Comment by jrfnl** [comment]
@photodude I'm looking into this now and am wondering whether you are passing a `tab-width` ? If not, that will be (part of) the problem, as without a tab-width setting, the sniff will always give inaccurate results.

**Comment by photodude** [comment]
@jrfnl Yes, we use Tab-width. in our ruleset.xml we have 
```xml
	<arg name="tab-width" value="4"/>
```

**Comment by gsherwood** [comment]
I can't replicate this error on 2.9.1. I can replicate the problem @jrfnl fixed with her PR (unreleased, but will be in 3.2.0) where the first line of the comment has too much whitespace now.

Here is my fixer output:
```
$ phpcs temp.php --standard=Generic --sniffs=Generic.WhiteSpace.DisallowSpaceIndent --tab-width=4 --report=diff -vvv

*** lots of verbose output here ***

	*** START FILE FIXING ***
---START FILE CONTENT---
 1|<?php
 2|class LoginViewLogin extends JViewLegacy
 3|{
 4|  	/**
 5|	 * Display the view.
 6|	 *
 7|	 * @param   string  $tpl  The name of the template file to parse.
 8|	 *
 9|	 * @return  void
10|	 *
11|	 * @since  3.7.0
12|	 */
13|	function foo() {}
14|}
15|
--- END FILE CONTENT ---
	E: [Line 4] Tabs must be used to indent lines; spaces are not allowed (Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed)
	Generic_Sniffs_WhiteSpace_DisallowSpaceIndentSniff (line 174) replaced token 11 (T_WHITESPACE) "··\t/**" => "\t··/**"
	* fixed 1 violations, starting loop 2 *
---START FILE CONTENT---
 1|<?php
 2|class LoginViewLogin extends JViewLegacy
 3|{
 4|	  /**
 5|	 * Display the view.
 6|	 *
 7|	 * @param   string  $tpl  The name of the template file to parse.
 8|	 *
 9|	 * @return  void
10|	 *
11|	 * @since  3.7.0
12|	 */
13|	function foo() {}
14|}
15|
--- END FILE CONTENT ---
	*** END FILE FIXING ***
--- temp.php
+++ PHP_CodeSniffer
@@ -1,7 +1,7 @@
 <?php
 class LoginViewLogin extends JViewLegacy
 {
-  	/**
+	  /**
 	 * Display the view.
 	 *
 	 * @param   string  $tpl  The name of the template file to parse.
```
And when running on master, you can see the difference in the fix:
```
	*** START FILE FIXING ***
---START FILE CONTENT---
 1|<?php
 2|class LoginViewLogin extends JViewLegacy
 3|{
 4|  	/**
 5|	 * Display the view.
 6|	 *
 7|	 * @param   string  $tpl  The name of the template file to parse.
 8|	 *
 9|	 * @return  void
10|	 *
11|	 * @since  3.7.0
12|	 */
13|	function foo() {}
14|}
15|
--- END FILE CONTENT ---
	E: [Line 4] Tabs must be used to indent lines; spaces are not allowed (Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed)
	PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\DisallowSpaceIndentSniff (line 195) replaced token 11 (T_WHITESPACE) "··\t/**" => "\t/**"
	* fixed 1 violations, starting loop 2 *
---START FILE CONTENT---
 1|<?php
 2|class LoginViewLogin extends JViewLegacy
 3|{
 4|	/**
 5|	 * Display the view.
 6|	 *
 7|	 * @param   string  $tpl  The name of the template file to parse.
 8|	 *
 9|	 * @return  void
10|	 *
11|	 * @since  3.7.0
12|	 */
13|	function foo() {}
14|}
15|
--- END FILE CONTENT ---
	*** END FILE FIXING ***
--- temp.php
+++ PHP_CodeSniffer
@@ -1,7 +1,7 @@
 <?php
 class LoginViewLogin extends JViewLegacy
 {
-  	/**
+	/**
 	 * Display the view.
 	 *
 	 * @param   string  $tpl  The name of the template file to parse.
```
But this sniff is never changing any of the other comment lines for me.

**Comment by gsherwood** [comment]
I should note that I also tested the actual file you linked and got the same result, but used a shorter file for my output.

**Comment by photodude** [comment]
Odd I just reran the test and I get the output you did. going from `space space tab` to `tab space space`

I'm now unable to replicate the issue I was seeing on Friday. (I hate when an issue seems so consistent but then stops being consistent. Guess it's time to turn it off and back on again)

As I'm oddly not able to replicate the issue I was seeing on Friday anymore, I guess I'll close this issue.

**Comment by gsherwood** [comment]
Thanks for getting back to me with your results.
