### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php:1050

### ISSUE THREAD

**Issue by sumnermic** [squizlabs/PHP_CodeSniffer#3196]
**Describe the bug**
The bug appears to be that $data is a string, not an array.

**Code sample**
```
<?php

function test()
{
    // test
    $a = 'test';

    $variable = [];
    foreach ($variable as $key => $value) {
        # code...
        $value = 'test';
    }
}
add_action('wp_head', 'test');
```

**Custom ruleset**
No custom ruleset, besides using **WordPress-Extra** Coding Standards.

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs --standard=WordPress-Extra /Users/michael.sumner/Desktop/test.php` (change to your path to test.php)
3. See error message displayed
```
mic@Mics-MacBook-Pro ~ % phpcs --standard=WordPress-Extra /Users/michael.sumner/Desktop/test.php
PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php:1050
Stack trace:
#0 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(1050): vsprintf('Expected exactl...', '\n')
#1 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(670): PHP_CodeSniffer\Files\File->addMessage(true, 'Expected exactl...', 3, 1, 'ExtraSpaceAfter...', '\n', 5, true)
#2 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(778): PHP_CodeSniffer\Files\File->addError('Expected exactl...', 2, 'ExtraSpaceAfter...', '\n', 0, true)
#3 /Users/michael.sumner/.composer/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php(395): PHP_CodeSniffer\Files\File->addFixableError('Expected exactl...', 2, 'ExtraSpaceAfter...', '\n')
#4 /Users/michael.sumner/.composer/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(910): WordPressCS\WordPress\Sniffs\WhiteSpace\ControlStructureSpacingSniff->process_token(2)
#5 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): WordPressCS\WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 2)
#6 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#7 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#8 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 {main}
  thrown in /Users/michael.sumner/.composer/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1050
```

**Expected behavior**
That the FatalError message will not be displayed.

**Versions (please complete the following information):**
 - OS: MacOS 11.1
 - PHP: 8.0.1
 - PHPCS: master
 - Standard: WordPress-Extra

**Additional context**
N/A

**Comment by gsherwood** [comment]
This is a problem with the WordPress sniff and not PHPCS. Looks like it has been fixed though: https://github.com/WordPress/WordPress-Coding-Standards/commit/7cd46bed1e6a7a2af3fe24c7f4a044da3076d8f4

**Comment by sumnermic** [comment]
I see thank you @gsherwood it appears that it still has to be released, thank you for locating this.

**Comment by wpbt** [comment]
with PHP v8.0.9 the fatal error still exists!
(WPCS and PHPCS versions: **Latest**)

**Comment by jrfnl** [comment]
@wpbt Wrong repo, not an issue in PHPCS.
